import {action} from "@storybook/addon-actions";
import Ranking from "../../src/components/organisms/Ranking";

const ranking = {
        "mode": {"id": 1, "name": "Version 1.5", "scoreType": ""},
        "difficulty": {"id": 4, "name": "Original"},
        "scores": [{
            "rank": 1,
            "value": 425027421,
            "player": {"id": 146, "name": "Rechiku"},
            "photo": "http://www.hostingpics.net/viewer.php?id=813400futari15Original351746382.jpg",
            "inp": "http",
            "replay": "http://www.youtube.com/watch?v=cFnEqP_UP_A&feature=youtu.be",
            "stage": "ALL",
            "id": 4,
            "comment": "All(Lx4) Reco Normal",
            "oneCC": true
        }, {
            "rank": 2,
            "value": 375804585,
            "player": {"id": 12, "name": "kawaijb"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 5,
            "comment": "Reco normal ALL (Lx2)",
            "oneCC": true
        }, {
            "rank": 3,
            "value": 351746382,
            "player": {"id": 150, "name": "Undef"},
            "photo": "http://www.hostingpics.net/viewer.php?id=813400futari15Original351746382.jpg",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 8894,
            "comment": "Reco Normale",
            "oneCC": true
        }, {
            "rank": 4,
            "value": 326813672,
            "player": {"id": 354, "name": "HUU"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 6,
            "comment": "Reco Normal",
            "oneCC": true
        }, {
            "rank": 5,
            "value": 277218745,
            "player": {"id": 14, "name": "Aliquantic"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 7,
            "comment": "Reco normal stage 5 Boss",
            "oneCC": false
        }, {
            "rank": 6,
            "value": 276836578,
            "player": {"id": 161, "name": "KAB"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 8,
            "comment": "Palm normal",
            "oneCC": true
        }, {
            "rank": 7,
            "value": 275250788,
            "player": {"id": 16, "name": "Sezi"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 9,
            "comment": "palm abnormal stage 5boss",
            "oneCC": false
        }, {
            "rank": 8,
            "value": 257262671,
            "player": {"id": 284, "name": "neo90"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 10,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 9,
            "value": 241314692,
            "player": {"id": 171, "name": "Y'om"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 11,
            "comment": "Reco Normal ALL(lx1)",
            "oneCC": true
        }, {
            "rank": 10,
            "value": 241163346,
            "player": {"id": 1, "name": "anzymus"},
            "photo": "http://hiscores.shmup.com/photos/1528479280588-20180608193220756x1008.jpg",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 14494,
            "comment": "",
            "oneCC": true
        }, {
            "rank": 11,
            "value": 231207990,
            "player": {"id": 586, "name": "E.T.E"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 12,
            "comment": "Palm Abnormal",
            "oneCC": true
        }, {
            "rank": 12,
            "value": 230076101,
            "player": {"id": 21, "name": "Zapbranisac"},
            "photo": "http://2drealfighter.free.fr/Scores/WP_20140103_014.jpg",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 4762,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 13,
            "value": 226914045,
            "player": {"id": 157, "name": "back"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 13,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 14,
            "value": 224546201,
            "player": {"id": 67, "name": "otaku"},
            "photo": "http://i1270.photobucket.com/albums/jj601/hotake06/1D5D4D7C-CBFC-4D0C-AACE-85C2FDC6A82F_zpskfyoc8rt.jpg",
            "inp": null,
            "replay": "",
            "stage": "5 BOSS",
            "id": 9139,
            "comment": "",
            "oneCC": false
        }, {
            "rank": 15,
            "value": 219068718,
            "player": {"id": 125, "name": "danmaker"},
            "photo": "",
            "inp": null,
            "replay": "",
            "stage": "5 BOSS",
            "id": 9012,
            "comment": "Reco, normal",
            "oneCC": false
        }, {
            "rank": 16,
            "value": 218461085,
            "player": {"id": 781, "name": "thetricker24"},
            "photo": "http://hiscores.shmup.com/photos/1439678593018-tmp243320150816004323636771770.jpg",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 9901,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 17,
            "value": 217488950,
            "player": {"id": 22, "name": "buddy"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 15,
            "comment": "Reco Normal  Boss",
            "oneCC": false
        }, {
            "rank": 18,
            "value": 209028910,
            "player": {"id": 23, "name": "skateinmars"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 16,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 19,
            "value": 208408686,
            "player": {"id": 24, "name": "Vincere"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 17,
            "comment": "Palm Abnormal ALL (Lx2)",
            "oneCC": true
        }, {
            "rank": 20,
            "value": 205172869,
            "player": {"id": 25, "name": "David333"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 18,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 21,
            "value": 195175742,
            "player": {"id": 26, "name": "Squidhead"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 19,
            "comment": "Reco normal Boss",
            "oneCC": false
        }, {
            "rank": 22,
            "value": 191145742,
            "player": {"id": 27, "name": "MLeJazz"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 20,
            "comment": "Reco normal",
            "oneCC": false
        }, {
            "rank": 23,
            "value": 187898361,
            "player": {"id": 28, "name": "Erhune"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 21,
            "comment": "Reco normal",
            "oneCC": true
        }, {
            "rank": 24,
            "value": 186838385,
            "player": {"id": 29, "name": "FEB"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 22,
            "comment": "Reco Normal  stage 5 boss",
            "oneCC": false
        }, {
            "rank": 25,
            "value": 185248619,
            "player": {"id": 269, "name": "Yami9999"},
            "photo": "http://i1073.photobucket.com/albums/w392/Yami9999/Mushihimesama%20Futari/MushihimesamaFutari_zps41160b87.png",
            "inp": null,
            "replay": "http://www.youtube.com/watch?v=cFnEqP_UP_A&feature=youtu.be",
            "stage": "ALL",
            "id": 5133,
            "comment": "Reco Normal",
            "oneCC": true
        }, {
            "rank": 26,
            "value": 180705508,
            "player": {"id": 30, "name": "Shadow gallery"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 23,
            "comment": "Reco normal",
            "oneCC": false
        }, {
            "rank": 27,
            "value": 176806114,
            "player": {"id": 31, "name": "Radegou"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 24,
            "comment": "palm abnormal",
            "oneCC": false
        }, {
            "rank": 28,
            "value": 171004726,
            "player": {"id": 52, "name": "Shardik"},
            "photo": "http://i39.servimg.com/u/f39/17/78/08/48/img_2032.jpg",
            "inp": null,
            "replay": "",
            "stage": "5",
            "id": 8757,
            "comment": "Reco / Normal",
            "oneCC": false
        }, {
            "rank": 29,
            "value": 166949057,
            "player": {"id": 32, "name": "Gatts"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 25,
            "comment": "Reco Normal",
            "oneCC": true
        }, {
            "rank": 30,
            "value": 162532434,
            "player": {"id": 33, "name": "Vanal"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 27,
            "comment": "Reco Normal Boss",
            "oneCC": false
        }, {
            "rank": 31,
            "value": 159861095,
            "player": {"id": 34, "name": "Colas"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 28,
            "comment": "Palm abnormal",
            "oneCC": false
        }, {
            "rank": 32,
            "value": 145344959,
            "player": {"id": 35, "name": "Dan"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "ALL",
            "id": 29,
            "comment": "Palm Abnormal",
            "oneCC": true
        }, {
            "rank": 33,
            "value": 137252757,
            "player": {"id": 36, "name": "GYO"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 30,
            "comment": "palm normal",
            "oneCC": false
        }, {
            "rank": 34,
            "value": 134832851,
            "player": {"id": 141, "name": "Lyv"},
            "photo": "",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 4785,
            "comment": "Palm abnormal",
            "oneCC": true
        }, {
            "rank": 35,
            "value": 127733870,
            "player": {"id": 37, "name": "Gabranth"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 31,
            "comment": "palm abnormal",
            "oneCC": false
        }, {
            "rank": 36,
            "value": 124236290,
            "player": {"id": 38, "name": "Dias Paddle"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 32,
            "comment": "Reco",
            "oneCC": false
        }, {
            "rank": 37,
            "value": 123493539,
            "player": {"id": 728, "name": "Aldherrian"},
            "photo": "",
            "inp": null,
            "replay": "",
            "stage": "5",
            "id": 8874,
            "comment": "Palm Abnormal",
            "oneCC": false
        }, {
            "rank": 38,
            "value": 117715931,
            "player": {"id": 39, "name": "Vince2"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 33,
            "comment": "Palm abnormal",
            "oneCC": false
        }, {
            "rank": 39,
            "value": 117458292,
            "player": {"id": 1649, "name": "GameOver"},
            "photo": "http://hiscores.shmup.com/photos/1553118009188-IMG06292Fotor.jpg",
            "inp": null,
            "replay": "",
            "stage": "5",
            "id": 15432,
            "comment": "",
            "oneCC": false
        }, {
            "rank": 40,
            "value": 112531595,
            "player": {"id": 40, "name": "Fairyliar"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 34,
            "comment": "reco normal",
            "oneCC": false
        }, {
            "rank": 41,
            "value": 110302226,
            "player": {"id": 41, "name": "Agalnarok"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 35,
            "comment": "Palm Abnormal",
            "oneCC": false
        }, {
            "rank": 42,
            "value": 109548225,
            "player": {"id": 42, "name": "Mickey"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 36,
            "comment": "Reco Normal",
            "oneCC": false
        }, {
            "rank": 43,
            "value": 101516851,
            "player": {"id": 1462, "name": "mutmut02"},
            "photo": "http://hiscores.shmup.com/photos/1490003634991-MushiFutari1.5OriginalRecoAbnormal.jpg",
            "inp": null,
            "replay": "",
            "stage": "ALL",
            "id": 13495,
            "comment": "Recco Abnormal",
            "oneCC": true
        }, {
            "rank": 44,
            "value": 99730296,
            "player": {"id": 163, "name": "coven"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 37,
            "comment": "Palm abnormal",
            "oneCC": false
        }, {
            "rank": 45,
            "value": 94315348,
            "player": {"id": 44, "name": "dodonpasim"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 38,
            "comment": "Reco normal",
            "oneCC": false
        }, {
            "rank": 46,
            "value": 94159914,
            "player": {"id": 45, "name": "snkpowa"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 39,
            "comment": "Palm Normal",
            "oneCC": false
        }, {
            "rank": 47,
            "value": 92606069,
            "player": {"id": 46, "name": "ixi"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 40,
            "comment": "Palm Abnormal",
            "oneCC": false
        }, {
            "rank": 48,
            "value": 89396631,
            "player": {"id": 47, "name": "ALFARABI"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "5",
            "id": 41,
            "comment": "Reco Normal",
            "oneCC": false
        }, {
            "rank": 49,
            "value": 82608434,
            "player": {"id": 48, "name": "Bestio"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 42,
            "comment": "normal Reco",
            "oneCC": false
        }, {
            "rank": 50,
            "value": 80410775,
            "player": {"id": 49, "name": "Kibo"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 43,
            "comment": "palm normal",
            "oneCC": false
        }, {
            "rank": 51,
            "value": 79961270,
            "player": {"id": 236, "name": "Crashdown"},
            "photo": "http://hiscores.shmup.com/photos/1568571742168-IMG20190915175818.jpg",
            "inp": null,
            "replay": "",
            "stage": "4",
            "id": 15875,
            "comment": "Reco Normal",
            "oneCC": false
        }, {
            "rank": 52,
            "value": 77708224,
            "player": {"id": 50, "name": "Sulf'"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 44,
            "comment": "Reco normal",
            "oneCC": false
        }, {
            "rank": 53,
            "value": 74909634,
            "player": {"id": 51, "name": "Prométherion"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 45,
            "comment": "Palm  Boss",
            "oneCC": false
        }, {
            "rank": 54,
            "value": 73272481,
            "player": {"id": 53, "name": "Jehuda"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "3",
            "id": 47,
            "comment": "Reco normal  Boss",
            "oneCC": false
        }, {
            "rank": 55,
            "value": 71190653,
            "player": {"id": 6, "name": "yace"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 48,
            "comment": "Palm  Boss",
            "oneCC": false
        }, {
            "rank": 56,
            "value": 67483163,
            "player": {"id": 54, "name": "BAD"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 49,
            "comment": "Reco Normal",
            "oneCC": false
        }, {
            "rank": 57,
            "value": 66968182,
            "player": {"id": 55, "name": "Arsene"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "3",
            "id": 50,
            "comment": "Palm normal Boss",
            "oneCC": false
        }, {
            "rank": 58,
            "value": 64347047,
            "player": {"id": 56, "name": "Johnny_Crypt"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 51,
            "comment": "Palm normal",
            "oneCC": false
        }, {
            "rank": 59,
            "value": 64134632,
            "player": {"id": 57, "name": "Akaimakai"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 52,
            "comment": "Recco normal",
            "oneCC": false
        }, {
            "rank": 60,
            "value": 58048852,
            "player": {"id": 58, "name": "Drunkenietzschigo"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 53,
            "comment": "Reco Normal",
            "oneCC": false
        }, {
            "rank": 61,
            "value": 55153250,
            "player": {"id": 94, "name": "Lone Rider"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "3",
            "id": 54,
            "comment": "Reco normal  Boss",
            "oneCC": false
        }, {
            "rank": 62,
            "value": 49692952,
            "player": {"id": 60, "name": "GaMeS"},
            "photo": null,
            "inp": null,
            "replay": null,
            "stage": "4",
            "id": 55,
            "comment": "palm abnormal",
            "oneCC": false
        }, {
            "rank": 63,
            "value": 43069442,
            "player": {"id": 169, "name": "Alptraum"},
            "photo": null,
            "inp": null,
            "replay": "",
            "stage": "3 BOSS",
            "id": 12137,
            "comment": "",
            "oneCC": false
        }, {
            "rank": 64,
            "value": 40954650,
            "player": {"id": 1520, "name": "Prickly Angler"},
            "photo": null,
            "inp": null,
            "replay": "",
            "stage": "4",
            "id": 16044,
            "comment": "Palm Normal",
            "oneCC": false
        }, {
            "rank": 65,
            "value": 16397006,
            "player": {"id": 1571, "name": "rentonl"},
            "photo": null,
            "inp": null,
            "replay": "",
            "stage": "3",
            "id": 14098,
            "comment": "",
            "oneCC": false
        }, {
            "rank": 66,
            "value": 14622560,
            "player": {"id": 468, "name": "banjo"},
            "photo": "",
            "inp": null,
            "replay": "",
            "stage": "2",
            "id": 3903,
            "comment": "reco\r\n",
            "oneCC": false
        }]
    };
export default {
    title: "Organism/Ranking",
};
export const defaultRanking = () => ({
    components: {Ranking},
    template: `
        <Ranking current-player-id="1" :ranking="ranking" @addScore="onAddScore" />`,
    data: () => ({ ranking}),
    methods: {
        onAddScore: action('onAddScore'),
    },
});

